<<<<<<< HEAD
# Update the wrangler.toml file with the correct compatibility settings
cat > wrangler.toml << 'EOF'
name = "jdue-api"
main = "worker/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
=======
name = "jdue-api"
main = "worker/index.js"
compatibility_date = "2024-08-13"
>>>>>>> b13afb2 (Configure frontend for production deployment with Cloudflare Workers API)

[[d1_databases]]
binding = "DB"
database_name = "jdue-production-db"
database_id = "4ecd4b97-a70c-4c18-9065-18e915be250a"

[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://jdue-cfv.pages.dev"

[build]
command = ""
<<<<<<< HEAD

# Add Node.js compatibility
node_compat = true
EOF
=======
>>>>>>> b13afb2 (Configure frontend for production deployment with Cloudflare Workers API)
